version: '2'
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
volumes:
  mssql-data: null
services:
  cassandra:
    image: 'cassandra:3.11.8'
    ports:
      - '9042:9042'
    volumes:
      - '.\data\cassandra:/var/lib/cassandra'
    environment:
      _JAVA_OPTIONS: '-Xms128m -Xmx256m'
    mem_limit: 512M
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
    mem_limit: 300M
    tmpfs: /datalog
    volumes: []
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_HEAP_OPTS: '-Xmx256M'
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.108
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    mem_limit: 512M
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04'
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: Qwerty-123
      MSSQL_MEMORY_LIMIT_MB: 500
    volumes:
      - 'mssql-data:/var/opt/mssql/data'
    mem_limit: 2G
  echo-server:
    image: eexit/mirror-http-server
    ports:
      - '9999:80'
    mem_limit: 50M
  smtp:
    image: mailhog/mailhog
    command:
      - '-smtp-bind-addr'
      - '0.0.0.0:25'
    user: root
    ports:
      - '8025:8025'
      - '25:25'
    mem_limit: 50M
  consul:
    image: 'consul:latest'
    ports:
      - '8500:8500'
    networks:
      default:
        ipv4_address: 172.28.1.1
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
    mem_limit: 512M
    volumes:
      - './configs/consul:/consul/config'
      - './data/consul:/consul/data'
  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
      JAVA_OPTS: '-Xmx256M'
    ports:
      - '9000:8080'
    mem_limit: 350M
  busybox:
    image: sequenceiq/busybox
    command: 'sh -c ''while sleep 3600; do :; done'''
    dns: 172.28.1.1
    mem_limit: 50M
  homer:
    image: b4bz/homer
    volumes:
      - '.\configs\homer\config.yml:/www/config.yml'
      - '.\configs\homer\assets:/www/assets'
    ports:
      - '8081:8080'
    restart: unless-stopped
    mem_limit: 50M
  traefik:
    image: 'traefik:v2.2'
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './configs/traefik:/etc/traefik/'
      - './certificates:/etc/traefik/certificates'
